# Generated by Django 4.1.10 on 2023-08-31 20:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fitnessgoal_progresstracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default=users.models.generate_objectid, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
