# Generated by Django 4.1.10 on 2023-08-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
    ]
